In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("winequality-white.csv", sep=';')
#df = pd.DataFrame(data)
da = pd.DataFrame(data)

In [3]:
da.sort_values("quality",ascending=False)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
827,7.4,0.24,0.36,2.00,0.031,27.0,139.0,0.99055,3.28,0.48,12.5,9
1605,7.1,0.26,0.49,2.20,0.032,31.0,113.0,0.99030,3.37,0.42,12.9,9
876,6.9,0.36,0.34,4.20,0.018,57.0,119.0,0.98980,3.28,0.36,12.7,9
774,9.1,0.27,0.45,10.60,0.035,28.0,124.0,0.99700,3.20,0.46,10.4,9
820,6.6,0.36,0.29,1.60,0.021,24.0,85.0,0.98965,3.41,0.61,12.4,9
...,...,...,...,...,...,...,...,...,...,...,...,...
1484,7.5,0.32,0.24,4.60,0.053,8.0,134.0,0.99580,3.14,0.50,9.1,3
2373,7.6,0.48,0.37,1.20,0.034,5.0,57.0,0.99256,3.05,0.54,10.4,3
251,8.5,0.26,0.21,16.20,0.074,41.0,197.0,0.99800,3.02,0.50,9.8,3
1688,6.7,0.25,0.26,1.55,0.041,118.5,216.0,0.99490,3.55,0.63,9.4,3
253,5.8,0.24,0.44,3.50,0.029,5.0,109.0,0.99130,3.53,0.43,11.7,3

In [8]:
da.sort_values("alcohol",ascending=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3265,4.2,0.215,0.23,5.10,0.041,64.0,157.0,0.99688,3.42,0.44,8.00,3
2625,4.5,0.190,0.21,0.95,0.033,89.0,159.0,0.99332,3.34,0.42,8.00,5
3839,6.2,0.310,0.23,3.30,0.052,34.0,113.0,0.99429,3.16,0.48,8.40,5
4020,6.4,0.370,0.12,5.90,0.056,6.0,91.0,0.99536,3.06,0.46,8.40,4
3835,6.2,0.310,0.23,3.30,0.052,34.0,113.0,0.99429,3.16,0.48,8.40,5
...,...,...,...,...,...,...,...,...,...,...,...,...
3904,5.0,0.455,0.18,1.90,0.036,33.0,106.0,0.98746,3.21,0.83,14.00,7
2945,4.9,0.330,0.31,1.20,0.016,39.0,150.0,0.98713,3.33,0.59,14.00,8
1099,5.8,0.290,0.21,2.60,0.025,12.0,120.0,0.98940,3.39,0.79,14.00,7
4503,5.8,0.610,0.01,8.40,0.041,31.0,104.0,0.99090,3.26,0.72,14.05,7
3918,6.4,0.350,0.28,1.60,0.037,31.0,113.0,0.98779,3.12,0.40,14.20,7